### ISSUE TITLE
Ability to change the duration

### ISSUE THREAD

**Issue by Frexuz** [Anonymous-Stranger/toast-manager#1]
Hi. Great little manager! :) I'm new to Polymer, so I'm not sure how I'd extend your element and make a pull request.

The duration is hard coded to 1500, would be nice to set that duration attribute on the `<toast-manager>` tag, and/or as a parameter in the `add()` function to be able to change it per-toast.

**Comment by Anonymous-Stranger** [comment]
Hello Kristian,

Thanks for your interest in it.

The duration is actually only hardcoded to default to 1500. You can set it
to whatever you want:

`<toast-manager toast-duration="2000"></toast-manager>`

I have updated the demo to show this as well.

Good luck; I hope this helps.

Cheers,
Ag

**Comment by Frexuz** [comment]
Thank you. I must have been confused, sorry my bad :D
